server.port=${PORT:5000}

jdbc.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.url=${JDBC_DATABASE_URL:}
hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
hibernate.hbm2ddl.auto=update
hibernate.cache.use_second_level_cache=true
hibernate.cache.use_query_cache=true
hibernate.cache.region.factory_class=org.hibernate.cache.ehcache.EhCacheRegionFactory
